# Generated by sila2.code_generator; sila2.__version__: 0.10.4
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.ursilainterface import SayHello_Responses, UrSilaInterfaceBase

#from .....Invoker.CommandTrigger import CommandTrigger
if TYPE_CHECKING:
    from ..server import Server


class UrSilaInterfaceImpl(UrSilaInterfaceBase):
    def __init__(self, parent_server: Server, ) -> None:
        super().__init__(parent_server=parent_server)
        #self.mInvokerDst = invokerDst

    def get_StartYear(self, *, metadata: MetadataDict) -> int:
        raise NotImplementedError  # TODO

    def SayHello(self, Name: str, *, metadata: MetadataDict) -> SayHello_Responses:
        #self.mInvokerDst.SendCommandToSecNodeUr({"who": "SilaService", "cmd": "running"})
        return SayHello_Responses("invoker with command send \"running\" triggered")
